/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AutenticadoRouteRouteImport } from './routes/_autenticado/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as AutenticadoAnoRouteImport } from './routes/_autenticado/ano'
import { Route as AutenticadoAuditoriaRouteImport } from './routes/_autenticado/auditoria'
import { Route as AutenticadoConversaRouteImport } from './routes/_autenticado/conversa'
import { Route as AutenticadoInsightsRouteImport } from './routes/_autenticado/insights'
import { Route as AutenticadoMercadoRouteImport } from './routes/_autenticado/mercado'
import { Route as AutenticadoMetasRouteImport } from './routes/_autenticado/metas'
import { Route as AutenticadoMinhaSegurancaRouteImport } from './routes/_autenticado/minha-seguranca'
import { Route as AutenticadoPainelRouteImport } from './routes/_autenticado/painel'
import { Route as AutenticadoResumoRouteImport } from './routes/_autenticado/resumo'
import { Route as AutenticadoSaudeRouteImport } from './routes/_autenticado/saude'
import { Route as ApiTtsRouteImport } from './routes/api/tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoRouteRoute = AutenticadoRouteRouteImport.update({
  id: '/_autenticado',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AutenticadoAnoRoute = AutenticadoAnoRouteImport.update({
  id: '/ano',
  path: '/ano',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoAuditoriaRoute = AutenticadoAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoConversaRoute = AutenticadoConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoInsightsRoute = AutenticadoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoMercadoRoute = AutenticadoMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoMetasRoute = AutenticadoMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoMinhaSegurancaRoute =
  AutenticadoMinhaSegurancaRouteImport.update({
    id: '/minha-seguranca',
    path: '/minha-seguranca',
    getParentRoute: () => AutenticadoRouteRoute,
  } as any)
const AutenticadoPainelRoute = AutenticadoPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoResumoRoute = AutenticadoResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const AutenticadoSaudeRoute = AutenticadoSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AutenticadoRouteRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/entrar': typeof EntrarRoute
  '/instalar': typeof InstalarRoute
  '/seguranca': typeof SegurancaRoute
  '/ano': typeof AutenticadoAnoRoute
  '/auditoria': typeof AutenticadoAuditoriaRoute
  '/conversa': typeof AutenticadoConversaRoute
  '/insights': typeof AutenticadoInsightsRoute
  '/mercado': typeof AutenticadoMercadoRoute
  '/metas': typeof AutenticadoMetasRoute
  '/minha-seguranca': typeof AutenticadoMinhaSegurancaRoute
  '/painel': typeof AutenticadoPainelRoute
  '/resumo': typeof AutenticadoResumoRoute
  '/saude': typeof AutenticadoSaudeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/entrar': typeof EntrarRoute
  '/instalar': typeof InstalarRoute
  '/seguranca': typeof SegurancaRoute
  '/ano': typeof AutenticadoAnoRoute
  '/auditoria': typeof AutenticadoAuditoriaRoute
  '/conversa': typeof AutenticadoConversaRoute
  '/insights': typeof AutenticadoInsightsRoute
  '/mercado': typeof AutenticadoMercadoRoute
  '/metas': typeof AutenticadoMetasRoute
  '/minha-seguranca': typeof AutenticadoMinhaSegurancaRoute
  '/painel': typeof AutenticadoPainelRoute
  '/resumo': typeof AutenticadoResumoRoute
  '/saude': typeof AutenticadoSaudeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_autenticado': typeof AutenticadoRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/entrar': typeof EntrarRoute
  '/instalar': typeof InstalarRoute
  '/seguranca': typeof SegurancaRoute
  '/_autenticado/ano': typeof AutenticadoAnoRoute
  '/_autenticado/auditoria': typeof AutenticadoAuditoriaRoute
  '/_autenticado/conversa': typeof AutenticadoConversaRoute
  '/_autenticado/insights': typeof AutenticadoInsightsRoute
  '/_autenticado/mercado': typeof AutenticadoMercadoRoute
  '/_autenticado/metas': typeof AutenticadoMetasRoute
  '/_autenticado/minha-seguranca': typeof AutenticadoMinhaSegurancaRoute
  '/_autenticado/painel': typeof AutenticadoPainelRoute
  '/_autenticado/resumo': typeof AutenticadoResumoRoute
  '/_autenticado/saude': typeof AutenticadoSaudeRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/entrar'
    | '/instalar'
    | '/seguranca'
    | '/ano'
    | '/auditoria'
    | '/conversa'
    | '/insights'
    | '/mercado'
    | '/metas'
    | '/minha-seguranca'
    | '/painel'
    | '/resumo'
    | '/saude'
    | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/entrar'
    | '/instalar'
    | '/seguranca'
    | '/ano'
    | '/auditoria'
    | '/conversa'
    | '/insights'
    | '/mercado'
    | '/metas'
    | '/minha-seguranca'
    | '/painel'
    | '/resumo'
    | '/saude'
    | '/api/tts'
  id:
    | '__root__'
    | '/'
    | '/_autenticado'
    | '/$'
    | '/entrar'
    | '/instalar'
    | '/seguranca'
    | '/_autenticado/ano'
    | '/_autenticado/auditoria'
    | '/_autenticado/conversa'
    | '/_autenticado/insights'
    | '/_autenticado/mercado'
    | '/_autenticado/metas'
    | '/_autenticado/minha-seguranca'
    | '/_autenticado/painel'
    | '/_autenticado/resumo'
    | '/_autenticado/saude'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutenticadoRouteRoute: typeof AutenticadoRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  EntrarRoute: typeof EntrarRoute
  InstalarRoute: typeof InstalarRoute
  SegurancaRoute: typeof SegurancaRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado': {
      id: '/_autenticado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AutenticadoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_autenticado/ano': {
      id: '/_autenticado/ano'
      path: '/ano'
      fullPath: '/ano'
      preLoaderRoute: typeof AutenticadoAnoRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/auditoria': {
      id: '/_autenticado/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AutenticadoAuditoriaRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/conversa': {
      id: '/_autenticado/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof AutenticadoConversaRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/insights': {
      id: '/_autenticado/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AutenticadoInsightsRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/mercado': {
      id: '/_autenticado/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof AutenticadoMercadoRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/metas': {
      id: '/_autenticado/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AutenticadoMetasRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/minha-seguranca': {
      id: '/_autenticado/minha-seguranca'
      path: '/minha-seguranca'
      fullPath: '/minha-seguranca'
      preLoaderRoute: typeof AutenticadoMinhaSegurancaRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/painel': {
      id: '/_autenticado/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AutenticadoPainelRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/resumo': {
      id: '/_autenticado/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AutenticadoResumoRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/_autenticado/saude': {
      id: '/_autenticado/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AutenticadoSaudeRouteImport
      parentRoute: typeof AutenticadoRouteRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AutenticadoRouteRouteChildren {
  AutenticadoAnoRoute: typeof AutenticadoAnoRoute
  AutenticadoAuditoriaRoute: typeof AutenticadoAuditoriaRoute
  AutenticadoConversaRoute: typeof AutenticadoConversaRoute
  AutenticadoInsightsRoute: typeof AutenticadoInsightsRoute
  AutenticadoMercadoRoute: typeof AutenticadoMercadoRoute
  AutenticadoMetasRoute: typeof AutenticadoMetasRoute
  AutenticadoMinhaSegurancaRoute: typeof AutenticadoMinhaSegurancaRoute
  AutenticadoPainelRoute: typeof AutenticadoPainelRoute
  AutenticadoResumoRoute: typeof AutenticadoResumoRoute
  AutenticadoSaudeRoute: typeof AutenticadoSaudeRoute
}

const AutenticadoRouteRouteChildren: AutenticadoRouteRouteChildren = {
  AutenticadoAnoRoute: AutenticadoAnoRoute,
  AutenticadoAuditoriaRoute: AutenticadoAuditoriaRoute,
  AutenticadoConversaRoute: AutenticadoConversaRoute,
  AutenticadoInsightsRoute: AutenticadoInsightsRoute,
  AutenticadoMercadoRoute: AutenticadoMercadoRoute,
  AutenticadoMetasRoute: AutenticadoMetasRoute,
  AutenticadoMinhaSegurancaRoute: AutenticadoMinhaSegurancaRoute,
  AutenticadoPainelRoute: AutenticadoPainelRoute,
  AutenticadoResumoRoute: AutenticadoResumoRoute,
  AutenticadoSaudeRoute: AutenticadoSaudeRoute,
}

const AutenticadoRouteRouteWithChildren =
  AutenticadoRouteRoute._addFileChildren(AutenticadoRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutenticadoRouteRoute: AutenticadoRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  EntrarRoute: EntrarRoute,
  InstalarRoute: InstalarRoute,
  SegurancaRoute: SegurancaRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
